export type BeneficiaryStatus = "Referred" | "Enrolled" | "Pending" | "Completed";

export interface RecommendedCourse {
  id: string;
  title: string;
  titleHi: string;
  nsqfLevel: number;
  duration: string;
  durationHi: string;
  distance: string;
  centreName: string;
  eligibility: string;
  mode: string;
  benefits: string[];
  matchTag: "High Match" | "Good Match" | "Recommended";
  nqrCode: string;
}

export interface TimelineEvent {
  step: string;
  title: string;
  date: string;
  actor: string;
  status: "done" | "current" | "upcoming";
  note: string;
}

export interface BeneficiaryRecord {
  id: string;
  shortId: string;
  name: string;
  nameHi: string;
  age: number;
  gender: "Male" | "Female";
  phone: string;
  district: string;
  state: string;
  education: string;
  educationHi: string;
  currentWork: string;
  currentWorkHi: string;
  interest: string;
  interestHi: string;
  mobility: string;
  preference: "Job" | "Self-Employment";
  preferenceHi: string;
  channel: "Web Voice" | "Facilitator Kiosk" | "WhatsApp Bot" | "IVR Call";
  language: string;
  status: BeneficiaryStatus;
  consentGiven: boolean;
  consentTimestamp: string;
  facilitatorId?: string;
  referral: {
    referralId: string;
    generatedOn: string;
    sharedTo: string;
    contactShared: string;
    agencyStatus: "Sent to Agency" | "Document Verified" | "Batch Assigned" | "Training Completed" | "Awaiting Referral";
    remarks: string;
    batchCode?: string;
  };
  recommendations: RecommendedCourse[];
  timeline: TimelineEvent[];
}

export const KPI_METRICS = {
  beneficiaries: {
    value: "1,248",
    numeric: 1248,
    label: "Beneficiaries",
    labelHi: "कुल लाभार्थी",
    delta: "+14.2% this month",
    subtext: "Voice & Kiosk profiled under PM-AJAY",
  },
  referrals: {
    value: "892",
    numeric: 892,
    label: "Referrals",
    labelHi: "जनरेटेड रेफरल",
    delta: "71.5% referral rate",
    subtext: "Shared with District Skill Agencies",
  },
  enrolled: {
    value: "436",
    numeric: 436,
    label: "Enrolled",
    labelHi: "प्रशिक्षण में नामांकित",
    delta: "48.9% conversion",
    subtext: "Active in NSQF-aligned batches",
  },
  completed: {
    value: "312",
    numeric: 312,
    label: "Completed",
    labelHi: "प्रशिक्षण पूर्ण",
    delta: "78.2% placed / self-employed",
    subtext: "Certified & linked to livelihood",
  },
};

export const TOP_SKILL_DEMANDS = [
  {
    skill: "Electrician",
    skillHi: "बिजली का काम (Electrician)",
    count: 320,
    perspectiveTarget: 280,
    nsqfLevel: "NSQF Level 4",
    color: "#1565D8",
  },
  {
    skill: "Tailoring",
    skillHi: "सिलाई / फैशन (Tailoring)",
    count: 210,
    perspectiveTarget: 230,
    nsqfLevel: "NSQF Level 3",
    color: "#2563EB",
  },
  {
    skill: "Computer",
    skillHi: "कंप्यूटर / डिजिटल काम",
    count: 180,
    perspectiveTarget: 160,
    nsqfLevel: "NSQF Level 3",
    color: "#3B82F6",
  },
  {
    skill: "Solar",
    skillHi: "सोलर तकनीशियन (Solar)",
    count: 130,
    perspectiveTarget: 100,
    nsqfLevel: "NSQF Level 4",
    color: "#60A5FA",
  },
  {
    skill: "Driving",
    skillHi: "वाहन चालन / मरम्मत (Driving)",
    count: 90,
    perspectiveTarget: 110,
    nsqfLevel: "NSQF Level 4",
    color: "#93C5FD",
  },
];

export const DISTRICT_DISTRIBUTION = [
  {
    district: "Nagpur",
    districtHi: "नागपुर",
    region: "Vidarbha, MH",
    beneficiaries: 542,
    referrals: 410,
    enrolled: 215,
    completed: 164,
    tier: "> 500",
    topSkill: "Electrician",
    agency: "District Skill Agency, Nagpur",
    coordinates: { x: 64, y: 46 },
  },
  {
    district: "Pune",
    districtHi: "पुणे",
    region: "Western MH",
    beneficiaries: 318,
    referrals: 224,
    enrolled: 108,
    completed: 76,
    tier: "100 - 500",
    topSkill: "Tailoring",
    agency: "District Skill Development Society, Pune",
    coordinates: { x: 32, y: 62 },
  },
  {
    district: "Nashik",
    districtHi: "नासिक",
    region: "North MH",
    beneficiaries: 186,
    referrals: 128,
    enrolled: 54,
    completed: 38,
    tier: "100 - 500",
    topSkill: "Computer",
    agency: "Nashik Zilla Kaushal Kendra",
    coordinates: { x: 30, y: 44 },
  },
  {
    district: "Aurangabad",
    districtHi: "छत्रपति संभाजीनगर",
    region: "Marathwada, MH",
    beneficiaries: 84,
    referrals: 58,
    enrolled: 28,
    completed: 18,
    tier: "50 - 100",
    topSkill: "Solar",
    agency: "Marathwada PM-AJAY Nodal Cell",
    coordinates: { x: 43, y: 50 },
  },
  {
    district: "Amravati",
    districtHi: "अमरावती",
    region: "Vidarbha, MH",
    beneficiaries: 68,
    referrals: 42,
    enrolled: 19,
    completed: 11,
    tier: "50 - 100",
    topSkill: "Electrician",
    agency: "Vidarbha Skill Mission, Amravati",
    coordinates: { x: 55, y: 44 },
  },
  {
    district: "Thane",
    districtHi: "ठाणे",
    region: "Konkan, MH",
    beneficiaries: 42,
    referrals: 25,
    enrolled: 10,
    completed: 4,
    tier: "10 - 50",
    topSkill: "Driving",
    agency: "Konkan Livelihood Agency",
    coordinates: { x: 22, y: 53 },
  },
  {
    district: "Gadchiroli",
    districtHi: "गड़चिरोली",
    region: "Vidarbha, MH",
    beneficiaries: 8,
    referrals: 5,
    enrolled: 2,
    completed: 1,
    tier: "< 10",
    topSkill: "Solar",
    agency: "Tribal & SC Sub-Plan Skill Unit",
    coordinates: { x: 72, y: 58 },
  },
];

export const BENEFICIARIES_DATA: BeneficiaryRecord[] = [
  {
    id: "PMAJAY-2026-00124",
    shortId: "PMAJAY-00124",
    name: "Rameshwar Wankhede",
    nameHi: "रामेश्वर वानखेड़े",
    age: 22,
    gender: "Male",
    phone: "+91 98234 51204",
    district: "Nagpur",
    state: "Maharashtra",
    education: "12th pass",
    educationHi: "12वीं पास (12th pass)",
    currentWork: "Farming",
    currentWorkHi: "खेती करता हूँ (Farming)",
    interest: "Electrical",
    interestHi: "बिजली का काम (Electrical work)",
    mobility: "20 km ke andar",
    preference: "Job",
    preferenceHi: "नौकरी (Job)",
    channel: "Web Voice",
    language: "Hindi",
    status: "Referred",
    consentGiven: true,
    consentTimestamp: "12 Aug 2026, 10:42 AM",
    facilitatorId: "FAC-NGP-018",
    referral: {
      referralId: "REF-2026-00124",
      generatedOn: "12 Aug 2026",
      sharedTo: "District Skill Agency, Nagpur",
      contactShared: "Yes (with consent)",
      agencyStatus: "Sent to Agency",
      remarks: "Beneficiary interested in electrician",
      batchCode: "NGP-ELEC-2026-B4",
    },
    recommendations: [
      {
        id: "CRS-ELEC-04",
        title: "Electrician (NSQF Level 4)",
        titleHi: "इलेक्ट्रीशियन (NSQF स्तर 4)",
        nsqfLevel: 4,
        duration: "3 Months",
        durationHi: "3 महीने (360 hrs)",
        distance: "12 km (Nagpur)",
        centreName: "Govt ITI & PM-AJAY Skill Centre, Nagpur",
        eligibility: "10th pass",
        mode: "Offline (ITI)",
        benefits: ["Government Certification", "Placement Support", "Free Tool-kit & Stipend"],
        matchTag: "High Match",
        nqrCode: "NQR/2026/PSS/0412",
      },
      {
        id: "CRS-SOLAR-04",
        title: "Solar Technician (NSQF Level 4)",
        titleHi: "सोलर तकनीशियन (NSQF स्तर 4)",
        nsqfLevel: 4,
        duration: "4 Months",
        durationHi: "4 महीने (420 hrs)",
        distance: "18 km (Nagpur)",
        centreName: "Surya Urja Kaushal Kendra, Kamptee Rd",
        eligibility: "10th pass",
        mode: "Offline (Skill Centre)",
        benefits: ["Surya Ghar Empanelment", "Placement Support"],
        matchTag: "Good Match",
        nqrCode: "NQR/2026/SGJ/0219",
      },
      {
        id: "CRS-MECH-03",
        title: "Two-Wheeler Mechanic (NSQF Level 3)",
        titleHi: "दोपहिया वाहन मैकेनिक (NSQF स्तर 3)",
        nsqfLevel: 3,
        duration: "3 Months",
        durationHi: "3 महीने (300 hrs)",
        distance: "10 km (Nagpur)",
        centreName: "Vidarbha Auto Skill Hub, Hingna",
        eligibility: "8th pass",
        mode: "Offline (Workshop)",
        benefits: ["Self-Employment Mudra Link", "Certification"],
        matchTag: "Recommended",
        nqrCode: "NQR/2026/ASC/0108",
      },
    ],
    timeline: [
      {
        step: "1.1 - 1.2",
        title: "Voice Onboarding & Data Usage Consent",
        date: "12 Aug 2026, 10:35 AM",
        actor: "Jeevika Saathi Voice Assistant (Hindi)",
        status: "done",
        note: "Audio consent recorded via Sarvam Saaras ASR.",
      },
      {
        step: "1.3 - 1.4",
        title: "8-Question Livelihood Interview & Profile Confirmation",
        date: "12 Aug 2026, 10:39 AM",
        actor: "Beneficiary / Facilitator Kiosk",
        status: "done",
        note: "Extracted 12th pass, Farming, Electrical work interest, 20 km mobility.",
      },
      {
        step: "1.5 - 1.6",
        title: "NSQF Recommendation & Course Selection",
        date: "12 Aug 2026, 10:41 AM",
        actor: "Skill Processing Engine",
        status: "done",
        note: "Ranked Top 3 NQR courses; Beneficiary selected Electrician (NSQF Level 4).",
      },
      {
        step: "1.7 / 3.4",
        title: "Referral Generated & Sent to District Skill Agency",
        date: "12 Aug 2026, 10:42 AM",
        actor: "District Officer Portal (REF-2026-00124)",
        status: "current",
        note: "Shared with District Skill Agency, Nagpur with beneficiary consent.",
      },
      {
        step: "Next",
        title: "Training Centre Verification & Batch Enrolment",
        date: "Scheduled",
        actor: "Govt ITI & PM-AJAY Skill Centre, Nagpur",
        status: "upcoming",
        note: "Awaiting seat confirmation in Batch NGP-ELEC-2026-B4.",
      },
    ],
  },
  {
    id: "PMAJAY-2026-00125",
    shortId: "PMAJAY-00125",
    name: "Savita Gaikwad",
    nameHi: "सविता गायकवाड़",
    age: 26,
    gender: "Female",
    phone: "+91 97652 11890",
    district: "Pune",
    state: "Maharashtra",
    education: "10th pass",
    educationHi: "10वीं पास (10th pass)",
    currentWork: "Homemaker",
    currentWorkHi: "गृहिणी हूँ (Homemaker)",
    interest: "Tailoring",
    interestHi: "सिलाई / फैशन (Tailoring & Fashion)",
    mobility: "10 km ke andar",
    preference: "Self-Employment",
    preferenceHi: "स्वरोज़गार (Self-Employment)",
    channel: "Facilitator Kiosk",
    language: "Marathi / Hindi",
    status: "Enrolled",
    consentGiven: true,
    consentTimestamp: "08 Aug 2026, 02:15 PM",
    facilitatorId: "FAC-PUN-009",
    referral: {
      referralId: "REF-2026-00125",
      generatedOn: "08 Aug 2026",
      sharedTo: "District Skill Development Society, Pune",
      contactShared: "Yes (with consent)",
      agencyStatus: "Batch Assigned",
      remarks: "Enrolled in Self-Employed Tailor NSQF Level 3 batch; interested in sewing machine grant.",
      batchCode: "PUN-TAIL-2026-B2",
    },
    recommendations: [
      {
        id: "CRS-TAIL-03",
        title: "Self-Employed Tailor (NSQF Level 3)",
        titleHi: "स्वरोज़गार दर्जी (NSQF स्तर 3)",
        nsqfLevel: 3,
        duration: "3 Months",
        durationHi: "3 महीने (340 hrs)",
        distance: "6 km (Pune)",
        centreName: "Savitribai Phule Kaushal Kendra, Hadapsar",
        eligibility: "8th pass",
        mode: "Offline (Skill Centre)",
        benefits: ["PM-AJAY Tool-kit Subsidy", "SHG Credit Linkage"],
        matchTag: "High Match",
        nqrCode: "NQR/2026/AMH/0301",
      },
    ],
    timeline: [
      {
        step: "1.1 - 1.4",
        title: "Facilitator Assisted Voice Profiling",
        date: "08 Aug 2026, 02:10 PM",
        actor: "Facilitator FAC-PUN-009",
        status: "done",
        note: "Completed in Marathi/Hindi voice mode.",
      },
      {
        step: "3.4",
        title: "Referral Accepted & Batch Enrolled",
        date: "10 Aug 2026, 11:20 AM",
        actor: "District Skill Development Society, Pune",
        status: "current",
        note: "Active in Batch PUN-TAIL-2026-B2 (Attendance: 94%).",
      },
    ],
  },
  {
    id: "PMAJAY-2026-00126",
    shortId: "PMAJAY-00126",
    name: "Akash Bhalerao",
    nameHi: "आकाश भालेराव",
    age: 20,
    gender: "Male",
    phone: "+91 94221 67341",
    district: "Nashik",
    state: "Maharashtra",
    education: "12th pass",
    educationHi: "12वीं पास (12th pass)",
    currentWork: "Studying",
    currentWorkHi: "पढ़ाई कर रहा हूँ (Studying)",
    interest: "Computer",
    interestHi: "कंप्यूटर / डिजिटल काम (Computer / Digital)",
    mobility: "15 km ke andar",
    preference: "Job",
    preferenceHi: "नौकरी (Job)",
    channel: "WhatsApp Bot",
    language: "Hindi",
    status: "Pending",
    consentGiven: true,
    consentTimestamp: "14 Aug 2026, 04:05 PM",
    referral: {
      referralId: "REF-2026-00126",
      generatedOn: "14 Aug 2026",
      sharedTo: "Nashik Zilla Kaushal Kendra",
      contactShared: "Yes (with consent)",
      agencyStatus: "Awaiting Referral",
      remarks: "Profile verified via WhatsApp voice flow; awaiting counsellor verification call.",
    },
    recommendations: [
      {
        id: "CRS-COMP-03",
        title: "Domestic Data Entry Operator (NSQF Level 3)",
        titleHi: "डेटा एंट्री ऑपरेटर (NSQF स्तर 3)",
        nsqfLevel: 3,
        duration: "3 Months",
        durationHi: "3 महीने (400 hrs)",
        distance: "8 km (Nashik)",
        centreName: "Nashik Digital Kaushal Hub, CBS",
        eligibility: "10th / 12th pass",
        mode: "Offline (Computer Lab)",
        benefits: ["IT-ITeS SSC Certification", "Local BPO Placement Drive"],
        matchTag: "High Match",
        nqrCode: "NQR/2026/ITS/0194",
      },
    ],
    timeline: [
      {
        step: "1.1 - 1.5",
        title: "WhatsApp Voice Note Interview Completed",
        date: "14 Aug 2026, 04:05 PM",
        actor: "WhatsApp Voice Flow",
        status: "current",
        note: "Pending final batch slot allocation at Nashik Zilla Kaushal Kendra.",
      },
    ],
  },
  {
    id: "PMAJAY-2026-00127",
    shortId: "PMAJAY-00127",
    name: "Prashant Meshram",
    nameHi: "प्रशांत मेश्राम",
    age: 24,
    gender: "Male",
    phone: "+91 91580 44912",
    district: "Nagpur",
    state: "Maharashtra",
    education: "12th pass",
    educationHi: "12वीं पास (12th pass)",
    currentWork: "Looking for work",
    currentWorkHi: "काम की तलाश में हूँ (Looking for work)",
    interest: "Solar",
    interestHi: "सोलर और बिजली कार्य (Solar & Electrical)",
    mobility: "25 km ke andar",
    preference: "Job",
    preferenceHi: "नौकरी (Job)",
    channel: "Web Voice",
    language: "Hindi",
    status: "Completed",
    consentGiven: true,
    consentTimestamp: "02 May 2026, 09:30 AM",
    referral: {
      referralId: "REF-2026-00127",
      generatedOn: "02 May 2026",
      sharedTo: "District Skill Agency, Nagpur",
      contactShared: "Yes (with consent)",
      agencyStatus: "Training Completed",
      remarks: "Certified in Solar PV Installer (NSQF Level 4); placed with Vidarbha Solar EPC Pvt Ltd.",
      batchCode: "NGP-SOL-2026-B1",
    },
    recommendations: [
      {
        id: "CRS-SOLAR-04",
        title: "Solar Technician (NSQF Level 4)",
        titleHi: "सोलर तकनीशियन (NSQF स्तर 4)",
        nsqfLevel: 4,
        duration: "4 Months",
        durationHi: "4 महीने (420 hrs)",
        distance: "14 km (Nagpur)",
        centreName: "Surya Urja Kaushal Kendra, Nagpur",
        eligibility: "10th pass",
        mode: "Offline (Skill Centre)",
        benefits: ["NSQF Level 4 Certificate", "₹16,500/mo Placement Offer"],
        matchTag: "High Match",
        nqrCode: "NQR/2026/SGJ/0219",
      },
    ],
    timeline: [
      {
        step: "Completed",
        title: "NSQF Level 4 Assessment Cleared & Placed",
        date: "04 Sep 2026",
        actor: "District Skill Agency, Nagpur",
        status: "done",
        note: "Placed as Junior Solar Technician at ₹16,500/month.",
      },
    ],
  },
  {
    id: "PMAJAY-2026-00128",
    shortId: "PMAJAY-00128",
    name: "Meenakshi सोनवणे (Sonawane)",
    nameHi: "मीनाक्षी सोनवणे",
    age: 23,
    gender: "Female",
    phone: "+91 98904 33120",
    district: "Aurangabad",
    state: "Maharashtra",
    education: "10th pass",
    educationHi: "10वीं पास (10th pass)",
    currentWork: "Small Family Shop",
    currentWorkHi: "अपना छोटा व्यवसाय है",
    interest: "Tailoring",
    interestHi: "सिलाई / फैशन (Tailoring)",
    mobility: "10 km ke andar",
    preference: "Self-Employment",
    preferenceHi: "स्वरोज़गार (Self-Employment)",
    channel: "IVR Call",
    language: "Hindi",
    status: "Enrolled",
    consentGiven: true,
    consentTimestamp: "09 Aug 2026, 01:15 PM",
    referral: {
      referralId: "REF-2026-00128",
      generatedOn: "09 Aug 2026",
      sharedTo: "Marathwada PM-AJAY Nodal Cell",
      contactShared: "Yes (with consent)",
      agencyStatus: "Batch Assigned",
      remarks: "Enrolled via Toll-Free IVR outbound callback.",
      batchCode: "AUR-TAIL-2026-B1",
    },
    recommendations: [
      {
        id: "CRS-TAIL-03",
        title: "Self-Employed Tailor (NSQF Level 3)",
        titleHi: "स्वरोज़गार दर्जी (NSQF स्तर 3)",
        nsqfLevel: 3,
        duration: "3 Months",
        durationHi: "3 महीने",
        distance: "5 km (Aurangabad)",
        centreName: "Dr. Ambedkar Kaushal Vikas Kendra",
        eligibility: "8th pass",
        mode: "Offline",
        benefits: ["PM-AJAY GIA Subsidy", "NSFDC Micro-Credit"],
        matchTag: "High Match",
        nqrCode: "NQR/2026/AMH/0301",
      },
    ],
    timeline: [],
  },
  {
    id: "PMAJAY-2026-00129",
    shortId: "PMAJAY-00129",
    name: "Swapnil Khobragade",
    nameHi: "स्वप्निल खोब्रागड़े",
    age: 21,
    gender: "Male",
    phone: "+91 96371 88210",
    district: "Nagpur",
    state: "Maharashtra",
    education: "10th pass",
    educationHi: "10वीं पास (10th pass)",
    currentWork: "Daily Wage Worker",
    currentWorkHi: "कहीं काम कर रहा हूँ",
    interest: "Driving",
    interestHi: "मशीन / वाहन मरम्मत एवं चालन",
    mobility: "20 km ke andar",
    preference: "Job",
    preferenceHi: "नौकरी (Job)",
    channel: "Facilitator Kiosk",
    language: "Hindi",
    status: "Referred",
    consentGiven: true,
    consentTimestamp: "13 Aug 2026, 05:20 PM",
    facilitatorId: "FAC-NGP-018",
    referral: {
      referralId: "REF-2026-00129",
      generatedOn: "13 Aug 2026",
      sharedTo: "District Skill Agency, Nagpur",
      contactShared: "Yes (with consent)",
      agencyStatus: "Sent to Agency",
      remarks: "Interested in Commercial LMV Driving + EV Maintenance.",
      batchCode: "NGP-DRV-2026-B2",
    },
    recommendations: [
      {
        id: "CRS-DRV-04",
        title: "Commercial Vehicle Driver & EV Care (NSQF Level 4)",
        titleHi: "वाणिज्यिक वाहन चालक (NSQF स्तर 4)",
        nsqfLevel: 4,
        duration: "2 Months",
        durationHi: "2 महीने",
        distance: "9 km (Nagpur)",
        centreName: "MSRTC & PM-AJAY Driving Institute, Nagpur",
        eligibility: "8th pass + Learner License",
        mode: "Offline (Track & Lab)",
        benefits: ["Driving License Support", "Fleet Partner Placement"],
        matchTag: "High Match",
        nqrCode: "NQR/2026/ASC/0402",
      },
    ],
    timeline: [],
  },
  {
    id: "PMAJAY-2026-00130",
    shortId: "PMAJAY-00130",
    name: "Pooja Ingole",
    nameHi: "पूजा इंगोले",
    age: 19,
    gender: "Female",
    phone: "+91 90114 72903",
    district: "Amravati",
    state: "Maharashtra",
    education: "12th pass",
    educationHi: "12वीं पास (12th pass)",
    currentWork: "Studying",
    currentWorkHi: "पढ़ाई कर रही हूँ",
    interest: "Computer",
    interestHi: "कंप्यूटर / डिजिटल काम",
    mobility: "12 km ke andar",
    preference: "Job",
    preferenceHi: "नौकरी (Job)",
    channel: "Web Voice",
    language: "Hindi",
    status: "Completed",
    consentGiven: true,
    consentTimestamp: "18 Apr 2026, 11:10 AM",
    referral: {
      referralId: "REF-2026-00130",
      generatedOn: "18 Apr 2026",
      sharedTo: "Vidarbha Skill Mission, Amravati",
      contactShared: "Yes (with consent)",
      agencyStatus: "Training Completed",
      remarks: "Completed Domestic Data Entry course; working at CSC Kendra.",
      batchCode: "AMR-COMP-2026-B1",
    },
    recommendations: [],
    timeline: [],
  },
  {
    id: "PMAJAY-2026-00131",
    shortId: "PMAJAY-00131",
    name: "Nitin Kamble",
    nameHi: "नितिन कांबले",
    age: 25,
    gender: "Male",
    phone: "+91 95456 20918",
    district: "Pune",
    state: "Maharashtra",
    education: "ITI / 12th",
    educationHi: "12वीं पास",
    currentWork: "Looking for work",
    currentWorkHi: "काम की तलाश में हूँ",
    interest: "Electrical",
    interestHi: "बिजली का काम (Electrical)",
    mobility: "20 km ke andar",
    preference: "Job",
    preferenceHi: "नौकरी (Job)",
    channel: "Web Voice",
    language: "Hindi",
    status: "Enrolled",
    consentGiven: true,
    consentTimestamp: "05 Aug 2026, 03:45 PM",
    referral: {
      referralId: "REF-2026-00131",
      generatedOn: "05 Aug 2026",
      sharedTo: "District Skill Development Society, Pune",
      contactShared: "Yes (with consent)",
      agencyStatus: "Batch Assigned",
      remarks: "Enrolled in Industrial Electrician NSQF Level 4.",
      batchCode: "PUN-ELEC-2026-B3",
    },
    recommendations: [],
    timeline: [],
  },
];

export const NQR_COURSES = [
  {
    code: "NQR/2026/PSS/0412",
    title: "Electrician (Distribution & Domestic)",
    titleHi: "इलेक्ट्रीशियन (घरेलू एवं वितरण)",
    sector: "Power & Electrical Sector Skill Council",
    nsqfLevel: 4,
    durationHours: 360,
    durationMonths: "3 Months",
    minEducation: "10th Pass",
    validTill: "31 Mar 2028",
    centresCount: 14,
    activeBeneficiaries: 320,
    schemeComponent: "PM-AJAY GIA Skill Development",
    placementRate: "81%",
  },
  {
    code: "NQR/2026/AMH/0301",
    title: "Self-Employed Tailor & Apparel Maker",
    titleHi: "स्वरोज़गार दर्जी एवं परिधान निर्माण",
    sector: "Apparel, Made-Ups & Home Furnishing SSC",
    nsqfLevel: 3,
    durationHours: 340,
    durationMonths: "3 Months",
    minEducation: "8th Pass",
    validTill: "30 Sep 2028",
    centresCount: 19,
    activeBeneficiaries: 210,
    schemeComponent: "PM-AJAY GIA + Tool-Kit Grant",
    placementRate: "76%",
  },
  {
    code: "NQR/2026/ITS/0194",
    title: "Domestic Data Entry & Digital Mitra",
    titleHi: "डेटा एंट्री ऑपरेटर एवं डिजिटल मित्र",
    sector: "IT-ITeS Sector Skill Council (NASSCOM)",
    nsqfLevel: 3,
    durationHours: 400,
    durationMonths: "3 Months",
    minEducation: "10th / 12th Pass",
    validTill: "31 Dec 2027",
    centresCount: 11,
    activeBeneficiaries: 180,
    schemeComponent: "PM-AJAY GIA Digital Inclusion",
    placementRate: "74%",
  },
  {
    code: "NQR/2026/SGJ/0219",
    title: "Solar PV Installer — Electrical (Suryamitra)",
    titleHi: "सोलर पीवी इंस्टॉलर (सूर्यमित्र)",
    sector: "Skill Council for Green Jobs",
    nsqfLevel: 4,
    durationHours: 420,
    durationMonths: "4 Months",
    minEducation: "10th Pass + Basic Math/Science",
    validTill: "30 Jun 2028",
    centresCount: 9,
    activeBeneficiaries: 130,
    schemeComponent: "PM-AJAY GIA Green Livelihoods",
    placementRate: "85%",
  },
  {
    code: "NQR/2026/ASC/0402",
    title: "Commercial Vehicle Driver & Two-Wheeler Service",
    titleHi: "वाणिज्यिक वाहन चालक एवं सर्विस तकनीशियन",
    sector: "Automotive Skills Development Council",
    nsqfLevel: 4,
    durationHours: 300,
    durationMonths: "2.5 Months",
    minEducation: "8th Pass",
    validTill: "31 Mar 2028",
    centresCount: 8,
    activeBeneficiaries: 90,
    schemeComponent: "PM-AJAY GIA Mobility & Transport",
    placementRate: "79%",
  },
];
